version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    # Security related PRs will ignore the following config.
    # See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#target-branch
    target-branch: latest-dependencies # Raise PRs for version updates against this branch
    labels:
      - "dependencies not-security" # Labels on PRs for version updates only
    allow:
      # Security updates
      - dependency-name: brakeman
        dependency-type: direct
      # Internal gems
      - dependency-name: "govuk*"
        dependency-type: direct
      - dependency-name: rubocop-govuk
        dependency-type: direct
      - dependency-name: scss_lint-govuk
        dependency-type: direct
      - dependency-name: gds-api-adapters
        dependency-type: direct
      - dependency-name: gds-sso
        dependency-type: direct
      - dependency-name: plek
        dependency-type: direct

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    # Security related PRs will ignore the following config.
    # See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#target-branch
    target-branch: latest-dependencies # Raise PRs for version updates against this branch
    labels:
      - "dependencies not-security" # Labels on PRs for version updates only
    allow:
      # Internal packages
      - dependency-name: stylelint-config-gds
        dependency-type: direct
      # Framework packages
      - dependency-name: standardx
        dependency-type: direct
      - dependency-name: stylelint
        dependency-type: direct
