---
version: 2
updates:
- package-ecosystem: bundler
  directory: /
  schedule:
    interval: daily
  cooldown:
    default-days: 10
- package-ecosystem: npm
  directory: /
  schedule:
    interval: daily
  cooldown:
    default-days: 10
...
